-- *********************************** SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: QA git test from slack, v3 by alexey.alferov+standent@sqldbm.com *


-- ************************************** DIm_Customer
CREATE TRANSIENT TABLE DIm_Customer
(
 CustomerId   int NOT NULL,
 CustomerName string NOT NULL,
 Phone        string,
 CONSTRAINT PK_table_2 PRIMARY KEY ( CustomerId )
)
STAGE_COPY_OPTIONS = 
( 
 ON_ERROR = CONTINUE
 PURGE = TRUE
 TRUNCATECOLUMNS = TRUE
 FORCE = TRUE
);

-- ************************************** DIm_Customer
CREATE VIEW DIm_Customer
  Comment = 'No Comment Provided'
AS
(
select * from dim_date
);

