-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** DIm_Customer
CREATE VIEW DIm_Customer
  Comment = 'No Comment Provided'
AS
(
select * from dim_date
);
